<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Biocuration2015 - Workshops</title>
        <!-- Bootstrap core CSS -->
        <link type='text/css' href="${host}/css/bootstrap.min.css" rel="stylesheet">
        <link type='text/css' href="${host}/css/footer.css" rel="stylesheet">
        <link type='text/css' href="${host}/css/myStyle.css" rel="stylesheet">
        <link type='text/css' href="${host}/css/doc.css" rel="stylesheet">
    </head>
    <body>
        <div id="wrap">
            <div class="container">
                <jsp:include page="/WEB-INF/inc/header.jsp" />
                <div class="row">
                    <jsp:include page="/WEB-INF/inc/sidebar.jsp"/>
                        <div class="col-md-9" id="main" style="margin-top:20px">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Workshops</h3>
                                </div>
                                <div class="panel-body">

                                    <h4 style="font-size:12pt">Workshop 1: Crowd/community curation: challenges & credit attribution</h4>
                                    <p>To be updated</p>

                                    <h4 style="font-size:12pt">Workshop 2: Data visualization & annotation</h4>
                                    <p>To be updated</p>


                                    <h4 style="font-size:12pt">Workshop 3: Biocuration in big data to knowledge: new strategy, process & framework</h4>
                                    <p>To be updated</p>


                                    <h4 style="font-size:12pt">Workshop 4: International collaboration in biocuration: projects & data/expertise sharing</h4>
                                    <p>
                                    	The manual curation of the information of data in biomedical resources is an expensive task. Sharing curation effort is a model already being adopted by several data resources including the Gene Ontology annotation effort and the IntAct molecular interaction database. In this workshop we will present examples of such efforts and will then like to open the floor for discussion on how to further develop such models and to explore how databases can make cost savings by sharing infrastructure and tool development to ensure that the data generated by public funding can have a greater longevity and minimise redundant development of resources by multiple disparate groups.
                                    </p>
                                    <p>Workshop format: ~45 minutes short talks, ~45 minutes open floor discussion</p>
                                   

                                    <h4 style="font-size:12pt">Workshop 5: Genotype-2-phenotype: Curation challenges in translational & reverse translational informatics</h4>
                                    <p>To be updated</p>


                                    <h4 style="font-size:12pt">Workshop 6: Money for biocuration: strategies, ideas & funding</h4>
                                    <p>
                                    Even though funding research infrastructures becomes more widespread, maintaining and growing existing databases is problematic, even for well-established databases. The recognition of the importance of curation still lags behind that of data generation and this is also reflected by funding policies. In this workshop we will discuss what the International Society for Biocuration (ISB), assisted by us curators, could do to improve the situation. Would it for example be appropriate to generate a letter of recommendation to increase funders awareness of the importance of biocuration, or publish a comment article advocating explicit funding for biocuration? Or what other kind of action(s) could be helpful? Additionally alternative business models besides licensing like e.g. pay-per use or crowd funding, are planned to be discussed.
                                    </p>
                                    <p>
                                    	To get an overview about the current financial situation of ISB members databases, we would like you to participate in <a href="https://www.surveymonkey.com/r/SBS8ZLP" target="_blank">this survey</a>. The statistics of the survey will be presented at the workshop.
                                    </p>
                                    
                                    <p>Workshop format: short talks, discussion</p>
                                    
                                    
                                    <h4 style="font-size:12pt">Special Workshop: Biocuration in China: importance, road map & priority</h4>
                                    <p>To be updated</p>


                                </div>
                            </div>
                        </div>
                    </div>
                    <!--row-->
                </div>
                <!--container end-->
            <jsp:include page="/WEB-INF/inc/footer.jsp"/>
        </div>
        <!--wrap-->

        <script src="${host}/js/jquery-1.11.1.min.js"></script>
        <script src="${host}/js/bootstrap.min.js"></script>

    </body>
</html>